spring:
  #jdbc配置
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver #com.mysql.cj.jdbc.Driver
    username: root
    password: root
    #jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    url: jdbc:p6spy:mysql://localhost:3306/test?allowMultiQueries=true&useSSL=false&serverTimezone=UTC

  #开启restful风格支持
  mvc:
    hiddenmethod:
      filter:
        enabled: true

        #文件上传的设置,必须设置，否则多文件上传大小出错
        #文件上传的设置,必须设置，否则多文件上传大小出错
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 500MB
      #thymeleaf的缓存是真的恶心，开发的时候一定要关了
  thymeleaf:
    cache: false
    #设置开发环境
  profiles:
    active: dev

#mybatis基本配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #在Mybatis的mapper.xml文件中resultType的type或者paramterType会返回自定义entity，
  #此时可以用全类名名来指定这些实体。可以使用type-aliases-package中指定entity扫描包类让mybatis自定扫描到自定义的entity。
 #设置封装实体类类的别名，批量设置别名
  type-aliases-package: com.fan.domain

#分页pageHelper
pagehelper:
  #分页的方言
  helper-dialect: mysql
  #分页的参数合理化，第一页前和最后一页后的处理
  reasonable: true
  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值;
  support-methods-arguments: true
  #支持通过Mapper接口参数来传递分页参数
  params: count=countSql

mybatis-plus:
  global-config:
    db-config:
      id-type: auto #主键策略,mysql是采取自增的
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2,步骤2: 实体类字段上加上@TableLogic注解)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true #可以不用配置,默认就是配置了true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输出sql语句的日志